const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Property = require('./models/Property');
const User = require('./models/User');

dotenv.config();

const propertiesData = [
  // 1. LUXURY PENTHOUSE (MUMBAI) - FOR SALE
  {
    title: 'The Sky Crest Signature Penthouse',
    description: 'An architectural masterpiece perched high above Worli Sea Face. This bespoke 4 BHK ultra-luxury duplex penthouse boasts unobstructed 270-degree views of the Arabian Sea, private rooftop plunge pool, italian marble flooring, and direct high-speed biometric elevators.',
    type: 'Penthouse',
    category: 'property',
    purpose: 'buy',
    price: 85000000,
    priceDisplay: '₹ 8.50 Cr',
    priceSub: '₹ 23,611 / Sq.Ft · 3,600 sq.ft',
    bhk: 4,
    area: 3600,
    location: { city: 'Mumbai', address: 'Worli Sea Face, Worli, Mumbai' },
    status: 'ready',
    statusLabel: 'Ready To Move',
    statusDate: 'Immediate possession',
    rera: true,
    reraId: 'MAHARERA/P51800039211',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Private Plunge Pool', 'Rooftop Deck', 'Private Elevator', '24x7 Concierge', 'Smart Home Automation', '3 Covered Car Parks', 'Gymnasium'],
    usps: ['Panoramic Arabian Sea view', 'Private rooftop deck with plunge pool', 'Direct private elevator access'],
    enquiries: 74,
    visits: 910,
    isFeatured: true,
  },

  // 2. BOTANICAL LUXURY VILLA (BENGALURU) - FOR SALE (NEW PROJECT)
  {
    title: 'Prestige Sanctuary Botanical Villas',
    description: 'Prestige Sanctuary is an exclusive collection of luxury 4 BHK villas nestled against the scenic foothills of Nandi Hills. Designed with biophilic architecture, open skylit courtyards, private lawns, zero-carbon solar capabilities, and a 50,000 sq.ft signature sports club.',
    type: 'Villa',
    category: 'project',
    purpose: 'buy',
    price: 32500000,
    priceDisplay: '₹ 3.25 Cr',
    priceSub: '₹ 10,156 / Sq.Ft · 3,200 sq.ft',
    bhk: 4,
    area: 3200,
    location: { city: 'Bengaluru', address: 'Nandi Hills Road, Devanahalli, Bengaluru' },
    status: 'uc',
    statusLabel: 'Under Construction',
    statusDate: 'Possession: Nov 2026',
    rera: true,
    reraId: 'PRM/KA/RERA/1251/446/PR/210819',
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Private Garden', 'Clubhouse', 'Infinity Pool', 'Tennis Court', 'EV Charging Station', '24x7 Security', 'Solar Power'],
    usps: ['Surrounded by 10,000+ trees', 'Solar-powered smart villas', 'Private courtyard garden'],
    enquiries: 96,
    visits: 1240,
    isFeatured: true,
  },

  // 3. AFFORDABLE 1 BHK APARTMENT (ANAND / GUJARAT) - FOR SALE
  {
    title: 'Bapa Madhav Anand Flats',
    description: 'Well-planned 1 BHK apartment situated near major educational institutions and business hubs in Vallabh Vidhyanagar, Anand. Perfect for single professionals, students, and first-time property investors.',
    type: '1 BHK Apartment',
    category: 'property',
    purpose: 'buy',
    price: 2551000,
    priceDisplay: '₹ 25.51 L',
    priceSub: '₹ 4,200 / Sq.Ft · 607 sq.ft',
    bhk: 1,
    area: 607,
    location: { city: 'Anand', address: 'Near Mota Bazaar, Vallabh Vidhyanagar, Anand' },
    status: 'uc',
    statusLabel: 'Under Construction',
    statusDate: 'Possession: Jun 2027',
    rera: true,
    reraId: 'GJ/ANAND/2023/001',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Covered Parking', 'CCTV Security', 'Elevator', 'Power Backup', '24x7 Water Supply'],
    usps: ['Gated community security', 'Dedicated covered car parking', 'Choice of modern modular interiors'],
    enquiries: 42,
    visits: 380,
  },

  // 4. MODERN 2 BHK RESIDENCE (AHMEDABAD) - FOR SALE
  {
    title: 'Adani Shantigram Aster Heights',
    description: 'Located in Ahmedabad’s most coveted township along SG Highway, this ready 2 BHK apartment in Aster Heights offers world-class clubhouse amenities, manicured landscapes, and exceptional connectivity.',
    type: '2 BHK Apartment',
    category: 'property',
    purpose: 'buy',
    price: 4800000,
    priceDisplay: '₹ 48.00 L',
    priceSub: '₹ 4,173 / Sq.Ft · 1,150 sq.ft',
    bhk: 2,
    area: 1150,
    location: { city: 'Ahmedabad', address: 'SG Highway, Near Vaishnodevi Circle, Ahmedabad' },
    status: 'ready',
    statusLabel: 'Ready To Move',
    statusDate: 'Immediate possession',
    rera: true,
    reraId: 'GJ/AHM/2023/0488',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1502005229762-ee1b2b93e083?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Golf Course Access', 'Clubhouse', 'Swimming Pool', 'Children Play Area', 'Gymnasium', 'Jogging Track'],
    usps: ['Within 600-acre township', 'Golf course adjacency', 'Direct SG Highway connectivity'],
    enquiries: 88,
    visits: 1120,
    isFeatured: true,
  },

  // 5. PREMIUM 3 BHK HIGH-RISE (GURUGRAM) - FOR RENT
  {
    title: 'Godrej Meridien Luxury Suites',
    description: 'Godrej Meridien is the epitome of fine living on Dwarka Expressway. Features a 66,000 sq.ft ultra-luxury clubhouse managed by international hospitality brands, Olympic-sized swimming pool, and VRV air-conditioned 3 BHK residences.',
    type: '3 BHK Apartment',
    category: 'property',
    purpose: 'rent',
    price: 65000,
    priceDisplay: '₹ 65,000 / mo',
    priceSub: 'Fully furnished · Maintenance included (Monthly Lease)',
    bhk: 3,
    area: 1950,
    location: { city: 'Gurugram', address: 'Dwarka Expressway, Sector 106, Gurugram' },
    status: 'ready',
    statusLabel: 'Ready To Move',
    statusDate: 'Immediate possession',
    rera: true,
    reraId: 'HRERA/GGM/2024/712',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Clubhouse', 'Olympic Pool', 'Spa by Elle', 'Tennis Court', 'Wine Tasting Lounge', 'EV Charging', 'Multi-tier Security'],
    usps: ['66,000 sq.ft grand clubhouse', 'Olympic-size all-weather pool', 'Butler & fine-dine services'],
    enquiries: 110,
    visits: 1350,
    isFeatured: true,
  },

  // 6. COMMERCIAL GRADE-A OFFICE (HYDERABAD) - FOR RENT
  {
    title: 'The Capital Tech Park Grade-A Office',
    description: 'Fully furnished, modern plug-and-play commercial office space in Hyderabad’s prime IT & Financial District. Accommodates 45 workstations, 3 executive director cabins, 14-seater board room, server room, and modern pantry.',
    type: 'Commercial',
    category: 'property',
    purpose: 'rent',
    price: 185000,
    priceDisplay: '₹ 1.85 L / mo',
    priceSub: '₹ 88 / Sq.Ft · 2,100 sq.ft (Monthly Lease)',
    bhk: 0,
    area: 2100,
    location: { city: 'Hyderabad', address: 'Financial District, HITEC City, Hyderabad' },
    status: 'ready',
    statusLabel: 'Ready To Move',
    statusDate: 'Immediate possession',
    rera: true,
    reraId: 'TS/HYD/2023/1044',
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Central Air Conditioning', '100% Power Backup', '10 High Speed Elevators', 'Cafeteria', 'Conference Facilities', 'Multi-level Parking'],
    usps: ['LEED Platinum Green building', 'High efficiency central chiller HVAC', '100% DG power backup & fiber grid'],
    enquiries: 45,
    visits: 520,
  },

  // 7. LUXURY ROW VILLA (VADODARA) - FOR SALE
  {
    title: 'Emerald Palms Row Villa',
    description: 'Beautiful triplex row house in the prime residential belt of Vasna-Bhayli Road. Features double-height living room ceilings, modern kitchen with granite platforms, attached servant room, and private rooftop entertainment deck.',
    type: 'Row House / Duplex',
    category: 'property',
    purpose: 'buy',
    price: 8800000,
    priceDisplay: '₹ 88.00 L',
    priceSub: '₹ 5,028 / Sq.Ft · 1,750 sq.ft',
    bhk: 3,
    area: 1750,
    location: { city: 'Vadodara', address: 'Vasna-Bhayli Road, Vadodara' },
    status: 'ready',
    statusLabel: 'Ready To Move',
    statusDate: 'Immediate possession',
    rera: true,
    reraId: 'GJ/VAD/2023/112',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Private Terrace', 'Covered Car Park', 'Gated Security', 'Community Garden', 'Solar Water Heater'],
    usps: ['Individual land title ownership', 'Private terrace gazebo setup', 'Quiet gated boutique community'],
    enquiries: 22,
    visits: 290,
  },

  // 8. GATED TOWNSHIP RESIDENTIAL PLOT (PUNE) - FOR SALE (NEW PROJECT)
  {
    title: 'The Meadowlands Gated Estate Plots',
    description: 'Pre-sanctioned non-agricultural (NA) residential plots in a pristine gated township with clear mountain views. Ready for custom villa construction with pre-laid underground utilities and wide tree-lined paved avenues.',
    type: 'Plot',
    category: 'project',
    purpose: 'buy',
    price: 6500000,
    priceDisplay: '₹ 65.00 L',
    priceSub: '₹ 2,708 / Sq.Ft · 2,400 sq.ft (NA Sanctioned)',
    bhk: 0,
    area: 2400,
    location: { city: 'Pune', address: 'Baner-Pashan Link Road, Pune' },
    status: 'ready',
    statusLabel: 'Ready To Move',
    statusDate: 'Immediate registration',
    rera: true,
    reraId: 'MAHARERA/P52100041289',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Gated Boundary Wall', 'Underground Cabling', 'Wide Asphalt Roads', 'Clubhouse', 'Street Lighting', '24x7 Security'],
    usps: ['100% Clear NA Plot titles', 'Underground electrical & water grid', 'Clubhouse & tennis facility'],
    enquiries: 58,
    visits: 670,
  },

  // 9. COMPACT STUDIO SUITE (BENGALURU) - FOR RENT
  {
    title: 'Urban Pod Studio Suites',
    description: 'Fully furnished, high-tech studio apartment designed for modern tech professionals on Bengaluru’s IT Corridor. Features automated smart lighting, fold-out Murphy bed, compact kitchenette, and co-working lounge.',
    type: 'Studio',
    category: 'property',
    purpose: 'rent',
    price: 24000,
    priceDisplay: '₹ 24,000 / mo',
    priceSub: 'Fully furnished · Maintenance included',
    bhk: 1,
    area: 450,
    location: { city: 'Bengaluru', address: 'Outer Ring Road, Marathahalli, Bengaluru' },
    status: 'ready',
    statusLabel: 'Ready To Move',
    statusDate: 'Immediate possession',
    rera: true,
    reraId: 'PRM/KA/RERA/1251/446/PR/200411',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Furnished Interiors', 'Launderette', 'Coworking Lounge', 'Gym', 'High Speed Wifi', 'Biometric Entry'],
    usps: ['Fully furnished with smart folding bed', 'Walking distance to tech parks', 'High rental demand'],
    enquiries: 62,
    visits: 780,
  },

  // 10. LUXURY 3 BHK APARTMENT (AHMEDABAD) - FOR SALE (NEW PROJECT)
  {
    title: 'The Crown Imperial Residences',
    description: 'The Crown Imperial offers ultra-chic 3 BHK luxury residences on Ahmedabad’s prestigious Sindhu Bhavan Road. Features towering 11-foot ceilings, soundproof double-glazed acoustic windows, and a panoramic rooftop deck.',
    type: '3 BHK Apartment',
    category: 'project',
    purpose: 'buy',
    price: 11500000,
    priceDisplay: '₹ 1.15 Cr',
    priceSub: '₹ 6,216 / Sq.Ft · 1,850 sq.ft',
    bhk: 3,
    area: 1850,
    location: { city: 'Ahmedabad', address: 'Sindhu Bhavan Road, Bodakdev, Ahmedabad' },
    status: 'uc',
    statusLabel: 'Under Construction',
    statusDate: 'Possession: Dec 2027',
    rera: true,
    reraId: 'GJ/AHM/2024/0912',
    images: [
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Sky Lounge', 'Infinity Pool', 'Banquet Hall', 'Indoor Squash Court', 'Double Basement Parking', 'High Speed Elevators'],
    usps: ['Prime Sindhu Bhavan Road address', 'Italian marble finish throughout', 'Sky lounge & rooftop infinity pool'],
    enquiries: 69,
    visits: 890,
    isFeatured: true,
  },

  // 11. HIGH STREET COMMERCIAL RETAIL SHOP (MUMBAI) - FOR RENT
  {
    title: 'Platina Galleria High-Street Retail Shop',
    description: 'Rare ground-floor commercial retail storefront available for lease on Linking Road, Bandra West. High-visibility double glass facade with heavy daily pedestrian traffic.',
    type: 'Commercial',
    category: 'property',
    purpose: 'rent',
    price: 250000,
    priceDisplay: '₹ 2.50 L / mo',
    priceSub: '₹ 294 / Sq.Ft · 850 sq.ft (Monthly Lease)',
    bhk: 0,
    area: 850,
    location: { city: 'Mumbai', address: 'Linking Road, Bandra West, Mumbai' },
    status: 'ready',
    statusLabel: 'Ready To Move',
    statusDate: 'Immediate possession',
    rera: true,
    reraId: 'MAHARERA/P51800019280',
    images: [
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Ground Floor Frontage', 'Glass Facade', 'Central HVAC', 'Dedicated Customer Parking', '24x7 Security'],
    usps: ['Direct Linking Road main frontage', 'High footfall shopping corridor', 'Ideal for jewelry, fashion, or cafe'],
    enquiries: 51,
    visits: 610,
  },

  // 12. GOLF RESIDENCE 5+ BHK VILLA (GURUGRAM) - FOR SALE (NEW PROJECT)
  {
    title: 'Sobha International City Golf Villa',
    description: 'Sobha International City is a 150-acre premier villa township on Dwarka Expressway. This presidential 5 BHK villa features private in-house elevator, imported German kitchen fittings, expansive landscaped terrace garden, and four covered parking bays.',
    type: 'Villa',
    category: 'project',
    purpose: 'buy',
    price: 65000000,
    priceDisplay: '₹ 6.50 Cr',
    priceSub: '₹ 12,500 / Sq.Ft · 5,200 sq.ft',
    bhk: 5,
    area: 5200,
    location: { city: 'Delhi NCR', address: 'Sector 109, Dwarka Expressway, Gurugram' },
    status: 'uc',
    statusLabel: 'Under Construction',
    statusDate: 'Possession: Oct 2026',
    rera: true,
    reraId: 'HRERA/GGM/2024/991',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Private Elevator', 'Private Lawns', 'Clubhouse', 'Golf Simulator', 'Heated Indoor Pool', '4 Car Parking Garage'],
    usps: ['Private elevator inside villa', 'Lush front & rear private lawns', 'Championship golf academy access'],
    enquiries: 84,
    visits: 1120,
    isFeatured: true,
  },

  // 13. MODERN 2 BHK LAKE VIEW APARTMENT (POWAI, MUMBAI) - FOR RENT
  {
    title: 'Hiranandani Powai Lakeview Condo',
    description: 'Immaculate neoclassical 2 BHK apartment in Hiranandani Gardens, Powai. Offers serene Powai Lake and hill views, Italian marble flooring, and modular kitchen with built-in appliances.',
    type: '2 BHK Apartment',
    category: 'property',
    purpose: 'rent',
    price: 52000,
    priceDisplay: '₹ 52,000 / mo',
    priceSub: 'Fully furnished · Modern neoclassical interiors',
    bhk: 2,
    area: 980,
    location: { city: 'Mumbai', address: 'Hiranandani Gardens, Powai, Mumbai' },
    status: 'ready',
    statusLabel: 'Ready To Move',
    statusDate: 'Immediate possession',
    rera: true,
    reraId: 'MAHARERA/P51800028910',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Clubhouse', 'Swimming Pool', 'Gymnasium', 'Squash Court', '24x7 Security', 'Covered Parking'],
    usps: ['Direct Powai Lake views', 'Walking distance to top international schools', 'Access to Forest Club'],
    enquiries: 48,
    visits: 630,
  },

  // 14. HERITAGE PORTUGUESE 4 BHK VILLA (GOA) - FOR SALE
  {
    title: 'Assagao Heritage Portuguese Villa',
    description: 'A restored Indo-Portuguese 4 BHK luxury estate in Assagao, Goa. Features high-pitched tiled ceilings, mother-of-pearl window inlays, expansive pool deck, and landscaped tropical gardens.',
    type: 'Villa',
    category: 'property',
    purpose: 'buy',
    price: 49000000,
    priceDisplay: '₹ 4.90 Cr',
    priceSub: '₹ 12,894 / Sq.Ft · 3,800 sq.ft (Private Pool)',
    bhk: 4,
    area: 3800,
    location: { city: 'Goa', address: 'Assagao Village, North Goa, Goa' },
    status: 'ready',
    statusLabel: 'Ready To Move',
    statusDate: 'Immediate possession',
    rera: true,
    reraId: 'GOA/RERA/2023/184',
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Private Swimming Pool', 'Landscaped Courtyard', 'Heritage Verandah', 'Servant Quarters', 'Solar Power Grid', '2 Car Garage'],
    usps: ['Private cobalt-blue swimming pool', 'Restored antique Goan architecture', 'Surrounded by lush mango & coconut groves'],
    enquiries: 65,
    visits: 820,
    isFeatured: true,
  },

  // 15. COMMERCIAL FLAGSHIP SHOWROOM (CYBER CITY, GURUGRAM) - FOR SALE
  {
    title: 'Cyber Greens Flagship Commercial Showroom',
    description: 'High-visibility ground and mezzanine commercial retail showroom space in the heart of DLF Cyber City. Ideal for luxury automobile showrooms, banking headquarters, or international fashion houses.',
    type: 'Commercial',
    category: 'property',
    purpose: 'buy',
    price: 42000000,
    priceDisplay: '₹ 4.20 Cr',
    priceSub: '₹ 15,000 / Sq.Ft · 2,800 sq.ft',
    bhk: 0,
    area: 2800,
    location: { city: 'Delhi NCR', address: 'DLF Cyber City, Phase 2, Gurugram' },
    status: 'ready',
    statusLabel: 'Ready To Move',
    statusDate: 'Immediate possession',
    rera: true,
    reraId: 'HRERA/GGM/2023/504',
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Glass Facade', 'Central Air Conditioning', 'Ample Basement Parking', '24x7 Security', 'Loading Bay Access'],
    usps: ['Prime Cyber City main avenue road visibility', 'High return on investment (8.2% gross yield)', 'Triple-height grand entrance facade'],
    enquiries: 39,
    visits: 490,
  },

  // 16. VIBRANT 1 BHK URBAN FLAT (BANDRA, MUMBAI) - FOR RENT
  {
    title: 'Bandra Hill View Contemporary 1 BHK',
    description: 'Chic 1 BHK apartment situated in Pali Hill, Bandra West. Equipped with designer custom carpentry, sleek wooden flooring, and high-speed fiber internet.',
    type: '1 BHK Apartment',
    category: 'property',
    purpose: 'rent',
    price: 38000,
    priceDisplay: '₹ 38,000 / mo',
    priceSub: 'Fully furnished · Prime Pali Hill location',
    bhk: 1,
    area: 580,
    location: { city: 'Mumbai', address: 'Pali Hill, Bandra West, Mumbai' },
    status: 'ready',
    statusLabel: 'Ready To Move',
    statusDate: 'Immediate possession',
    rera: true,
    reraId: 'MAHARERA/P51800010992',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Modular Kitchen', 'Air Conditioning', 'Elevator', 'Security', 'Intercom'],
    usps: ['Walking distance to cafes & restaurants', 'Designer lighting & modular kitchen', 'Peaceful quiet upscale lane'],
    enquiries: 56,
    visits: 740,
  },

  // 17. SMART DESIGNER STUDIO (BKC, MUMBAI) - FOR SALE
  {
    title: 'BKC Smart Suites Luxury Studio',
    description: 'Designer studio suite right next to BKC financial core. Features German-engineered smart space-saving furniture, concealed climate control, and digital keyless door locks.',
    type: 'Studio',
    category: 'property',
    purpose: 'buy',
    price: 8500000,
    priceDisplay: '₹ 85.00 L',
    priceSub: '₹ 17,346 / Sq.Ft · 490 sq.ft',
    bhk: 1,
    area: 490,
    location: { city: 'Mumbai', address: 'Bandra Kurla Complex (BKC), Mumbai' },
    status: 'ready',
    statusLabel: 'Ready To Move',
    statusDate: 'Immediate possession',
    rera: true,
    reraId: 'MAHARERA/P51800044991',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Business Lounge', 'Gymnasium', 'Rooftop Cafe', 'Automated Car Parking', 'Biometric Security'],
    usps: ['Opposite leading financial headquarters in BKC', 'Zero commute for finance & tech professionals', 'High rental yield potential'],
    enquiries: 42,
    visits: 580,
  },

  // 18. PREMIUM VILLA PLOT (GIFT CITY, GANDHINAGAR) - FOR SALE (NEW PROJECT)
  {
    title: 'GIFT City International Enclave Plots',
    description: 'Exclusive villa plots situated within the residential precinct of GIFT City, Gandhinagar. Connected to global financial headquarters, international school campuses, and metro network.',
    type: 'Plot',
    category: 'project',
    purpose: 'buy',
    price: 9500000,
    priceDisplay: '₹ 95.00 L',
    priceSub: '₹ 3,064 / Sq.Ft · 3,100 sq.ft (RERA Approved)',
    bhk: 0,
    area: 3100,
    location: { city: 'Ahmedabad', address: 'GIFT City Zone, Gandhinagar, Ahmedabad' },
    status: 'uc',
    statusLabel: 'Under Construction',
    statusDate: 'Possession: Jun 2028',
    rera: true,
    reraId: 'GJ/GIFT/2024/007',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Underground Utility Grid', 'Smart City Fiber Network', 'Clubhouse', 'Parks & Playgrounds', '24x7 Security Surveillance'],
    usps: ['Located inside India’s premier Smart FinTech City', 'Underground utility tunnels & district cooling grid', 'Unmatched capital appreciation prospect'],
    enquiries: 78,
    visits: 990,
  },

  // 19. PRESIDENTIAL 5+ BHK PALACE ESTATE (HYDERABAD) - FOR SALE
  {
    title: 'Jubilee Hills Presidential Mansion',
    description: 'An ultra-luxury bespoke 5 BHK residential mansion in the elite enclave of Jubilee Hills, Hyderabad. Designed by celebrated interior architects featuring private elevators and a 12-seater private cinema.',
    type: 'Villa',
    category: 'property',
    purpose: 'buy',
    price: 145000000,
    priceDisplay: '₹ 14.50 Cr',
    priceSub: '₹ 19,333 / Sq.Ft · 7,500 sq.ft',
    bhk: 5,
    area: 7500,
    location: { city: 'Hyderabad', address: 'Road No. 36, Jubilee Hills, Hyderabad' },
    status: 'ready',
    statusLabel: 'Ready To Move',
    statusDate: 'Immediate possession',
    rera: true,
    reraId: 'TS/HYD/2023/901',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Private Cinema', 'Indoor Swimming Pool', 'Private Elevator', 'Wine Cellar', '6 Covered Car Garage', '24x7 Armed Guard Booth'],
    usps: ['Private 12-seater Dolby Atmos home theater', 'Temperature-controlled indoor swimming pool', 'Grand landscaped terrace with waterfall'],
    enquiries: 31,
    visits: 410,
    isFeatured: true,
  },

  // 20. SCENIC 2 BHK CONDOS (PUNE) - FOR SALE (NEW PROJECT)
  {
    title: 'Kolte Patil Life Republic Greens',
    description: 'Thoughtfully designed 2 BHK apartments in Pune’s celebrated Life Republic township at Hinjewadi. Complete with world-class sporting arenas and nature trails.',
    type: '2 BHK Apartment',
    category: 'project',
    purpose: 'buy',
    price: 6200000,
    priceDisplay: '₹ 62.00 L',
    priceSub: '₹ 5,740 / Sq.Ft · 1,080 sq.ft',
    bhk: 2,
    area: 1080,
    location: { city: 'Pune', address: 'Hinjewadi IT Hub, Pune' },
    status: 'uc',
    statusLabel: 'Under Construction',
    statusDate: 'Possession: Aug 2027',
    rera: true,
    reraId: 'MAHARERA/P52100033100',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Clubhouse', 'Olympic Swimming Pool', 'Cricket Ground', 'Badminton Courts', 'Jogging Track', 'EV Charging Grid'],
    usps: ['Within 400-acre township with international school', 'Direct 5-minute commute to Hinjewadi Phase 1 & 2', 'Over 70% open green landscapes'],
    enquiries: 89,
    visits: 1150,
  },

  // 21. STYLISH 3 BHK GARDEN DUPLEX (INDIRANAGAR, BENGALURU) - FOR RENT
  {
    title: 'Indiranagar Boutique Garden Duplex',
    description: 'Charming modern duplex residence in Indiranagar. Featuring double-height living spaces, teak-wood staircase, private shaded garden patio, and custom furniture.',
    type: 'Row House / Duplex',
    category: 'property',
    purpose: 'rent',
    price: 75000,
    priceDisplay: '₹ 75,000 / mo',
    priceSub: 'Fully furnished · Private garden deck',
    bhk: 3,
    area: 2100,
    location: { city: 'Bengaluru', address: '100ft Road, Indiranagar, Bengaluru' },
    status: 'ready',
    statusLabel: 'Ready To Move',
    statusDate: 'Immediate possession',
    rera: true,
    reraId: 'PRM/KA/RERA/1251/446/PR/190802',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Private Garden', 'Modular Kitchen', 'Air Conditioning', '100% Power Backup', 'Covered Parking'],
    usps: ['Private ground-floor garden with wooden deck', 'Walking distance to 100ft Road gourmet cafes', 'High-ceiling wooden loft master suite'],
    enquiries: 61,
    visits: 790,
  },

  // 22. BOUTIQUE COMMERCIAL OFFICE (BKC, MUMBAI) - FOR SALE
  {
    title: 'One BKC Corporate Executive Office',
    description: 'Premium commercial office in One BKC. Designed for hedge funds, law firms, and tech headquarters with reception lobby, conference suite, and workstations.',
    type: 'Commercial',
    category: 'property',
    purpose: 'buy',
    price: 38000000,
    priceDisplay: '₹ 3.80 Cr',
    priceSub: '₹ 23,030 / Sq.Ft · 1,650 sq.ft',
    bhk: 0,
    area: 1650,
    location: { city: 'Mumbai', address: 'G Block, Bandra Kurla Complex (BKC), Mumbai' },
    status: 'ready',
    statusLabel: 'Ready To Move',
    statusDate: 'Immediate possession',
    rera: true,
    reraId: 'MAHARERA/P51800021455',
    images: [
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Centrally Air Conditioned', 'BMS Automation', '6 High Speed Elevators', 'Executive Lounge', 'Valet Parking'],
    usps: ['Prestigious G Block BKC corporate address', 'High rental yield for institutional corporate lease', 'Double-glazed soundproof glass walls'],
    enquiries: 36,
    visits: 480,
  },

  // 23. COASTAL FARMHOUSE ESTATE (ALIBAUG) - FOR SALE
  {
    title: 'Awas Beach Luxury Farmhouse Estate',
    description: 'Quarter-acre fertile coastal farmhouse estate in Awas, Alibaug. Surrounded by coconut groves, with road access, water connection, designer 4 BHK villa, private plunge pool, and 24x7 security.',
    type: 'Farmhouse',
    category: 'property',
    purpose: 'buy',
    price: 34500000,
    priceDisplay: '₹ 3.45 Cr',
    priceSub: '₹ 3,136 / Sq.Ft · 11,000 sq.ft (Quarter Acre)',
    bhk: 4,
    area: 11000,
    location: { city: 'Mumbai', address: 'Awas Coastal Belt, Alibaug, Mumbai' },
    status: 'ready',
    statusLabel: 'Ready To Move',
    statusDate: 'Immediate registration',
    rera: true,
    reraId: 'MAHARERA/P52000018820',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Private Pool', 'Organic Vegetable Garden', 'Gated Compound Wall', 'Fresh Water Borewell', '3-Phase Electricity', 'Mature Coconut & Mango Trees', '24x7 Security'],
    usps: ['5-minute walk to pristine Awas Beach', '15-minute speed boat ride from Gateway of India, Mumbai', 'Clear NA Farmhouse Title with private pool & orchard'],
    enquiries: 54,
    visits: 720,
    isFeatured: true,
  },

  // 24. SIGNATURE SEA VIEW 4 BHK RESIDENCE (WORLI, MUMBAI) - FOR RENT
  {
    title: 'Lodha Park Signature Sea Facing 4 BHK',
    description: 'High-floor 4 BHK residence in Lodha Park, Worli with views of the Arabian Sea and Bandra-Worli Sea Link. Fully fitted with Poggenpohl kitchen and Armani/Casa designer finishes.',
    type: '4 BHK Apartment',
    category: 'property',
    purpose: 'rent',
    price: 185000,
    priceDisplay: '₹ 1.85 L / mo',
    priceSub: 'Fully furnished · Panoramic sea view',
    bhk: 4,
    area: 2800,
    location: { city: 'Mumbai', address: 'Pandurang Budhkar Marg, Worli, Mumbai' },
    status: 'ready',
    statusLabel: 'Ready To Move',
    statusDate: 'Immediate possession',
    rera: true,
    reraId: 'MAHARERA/P51800029311',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['7-Acre Private Park', '6 Swimming Pools', 'Spa & Salon', 'Banquet Hall', '3 Covered Car Parks', 'Helipad Access'],
    usps: ['7-acre private urban park', 'Unobstructed Bandra-Worli Sea Link views', 'Concierge by Saint Amand'],
    enquiries: 72,
    visits: 930,
  },

  // 25. GREEN VALLEY SERENE COUNTRY FARMHOUSE (GURUGRAM / SOHNA) - FOR SALE
  {
    title: 'Sohna Green Valley Serene Country Farmhouse',
    description: 'Expansive 14,000 sq.ft country farmhouse nestled along the scenic foothills of the Aravalli hills on Sohna Road, Gurugram. Features 4 opulent bedroom suites, floor-to-ceiling glass pavilions, private pool, and mature fruit gardens.',
    type: 'Farmhouse',
    category: 'property',
    purpose: 'buy',
    price: 48500000,
    priceDisplay: '₹ 4.85 Cr',
    priceSub: '₹ 3,464 / Sq.Ft · 14,000 sq.ft (Private Gated Estate)',
    bhk: 4,
    area: 14000,
    location: { city: 'Delhi NCR', address: 'Sohna Road, Golf Course Extension, Gurugram' },
    status: 'ready',
    statusLabel: 'Ready To Move',
    statusDate: 'Immediate registration',
    rera: true,
    reraId: 'HRERA/GGM/2023/1982',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Private Pool', 'Orchard & Gazebo', 'Gated Security', 'EV Charging Station', 'Solar Power', 'Staff Quarters', 'Badminton Court'],
    usps: ['Surrounded by Aravalli foothills & landscaped lawns', 'Private temperature-controlled swimming pool', 'Organic fruit orchards with gazebo dining'],
    enquiries: 65,
    visits: 890,
    isFeatured: true,
  },

  // 26. LODHA WORLD ONE SKYLINE PENTHOUSE (MUMBAI) - FOR SALE
  {
    title: 'Lodha World One Skyline Penthouse',
    description: 'Iconic ultra-luxury 4 BHK duplex penthouse soaring above Mumbai’s skyline in Lower Parel. Features private sky-terrace, Armani/Casa interiors, 360-degree panoramic city & sea views, and private elevators.',
    type: 'Penthouse',
    category: 'property',
    purpose: 'buy',
    price: 420000000,
    priceDisplay: '₹ 42.00 Cr',
    priceSub: '₹ 70,000 / Sq.Ft · 6,000 sq.ft',
    bhk: 4,
    area: 6000,
    location: { city: 'Mumbai', address: 'Senapati Bapat Marg, Lower Parel, Mumbai' },
    status: 'ready',
    statusLabel: 'Ready To Move',
    statusDate: 'Immediate possession',
    rera: true,
    reraId: 'MAHARERA/P51800008811',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Private Sky Deck', 'Private Pool', 'Concierge Service', 'Private Biometric Elevator', '4 Covered Car Parks', 'Helipad Access'],
    usps: ['Iconic skyscraper landmark in Lower Parel', 'Custom Armani/Casa interior styling', 'Unmatched 360-degree city & sea views'],
    enquiries: 48,
    visits: 590,
    isFeatured: true,
  },

  // 27. TOTAL ENVIRONMENT IN THAT QUIET EARTH (BENGALURU) - FOR SALE (NEW PROJECT)
  {
    title: 'Total Environment In That Quiet Earth',
    description: 'Handcrafted earth-sheltered luxury 3 BHK residences with private terrace gardens featuring creeping ivy and natural stone finishes. Located on Hennur Main Road.',
    type: '3 BHK Apartment',
    category: 'project',
    purpose: 'buy',
    price: 24500000,
    priceDisplay: '₹ 2.45 Cr',
    priceSub: '₹ 10,208 / Sq.Ft · 2,400 sq.ft',
    bhk: 3,
    area: 2400,
    location: { city: 'Bengaluru', address: 'Hennur Main Road, Off New Airport Road, Bengaluru' },
    status: 'uc',
    statusLabel: 'Under Construction',
    statusDate: 'Possession: Jun 2027',
    rera: true,
    reraId: 'PRM/KA/RERA/1251/446/PR/180521',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Private Terrace Garden', 'Clubhouse', 'Swimming Pool', 'Tennis Court', 'Squash Court', 'Lush Green Canopy'],
    usps: ['Signature handcrafted earth architecture', 'Private garden on every floor level', 'Zero vehicular movement on ground surface'],
    enquiries: 92,
    visits: 1180,
    isFeatured: true,
  },

  // 28. DLF THE CREST ULTRAMODERN RESIDENCE (GURUGRAM) - FOR SALE
  {
    title: 'DLF The Crest Ultramodern Residence',
    description: 'A benchmark in luxury living. Spacious 4 BHK apartment with high ceilings, private lift lobbies, and floor-to-ceiling glass windows overlooking the DLF Golf Course.',
    type: '4 BHK Apartment',
    category: 'property',
    purpose: 'buy',
    price: 72000000,
    priceDisplay: '₹ 7.20 Cr',
    priceSub: '₹ 20,571 / Sq.Ft · 3,500 sq.ft',
    bhk: 4,
    area: 3500,
    location: { city: 'Delhi NCR', address: 'Golf Course Road, DLF Phase 5, Gurugram' },
    status: 'ready',
    statusLabel: 'Ready To Move',
    statusDate: 'Immediate possession',
    rera: true,
    reraId: 'HRERA/GGM/2017/08',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Private Lift Lobby', 'Clubhouse', 'Resort Pool', 'Tennis Courts', 'Multi-tier Security', '3 Reserved Parking Slots'],
    usps: ['Prime Golf Course Road location', 'Private air-conditioned lobby on each floor', 'Designed by world-renowned architect Hafeez Contractor'],
    enquiries: 77,
    visits: 980,
  },

  // 29. AMANORA GATEWAY TOWERS MARVEL SUITES (PUNE) - FOR SALE (NEW PROJECT)
  {
    title: 'Amanora Gateway Towers Marvel Suites',
    description: 'Swarovski crystal-accented 3 BHK designer homes in Amanora Park Town, Hadapsar. Offers seamless smart automation and 400-acre integrated township lifestyle.',
    type: '3 BHK Apartment',
    category: 'project',
    purpose: 'buy',
    price: 16500000,
    priceDisplay: '₹ 1.65 Cr',
    priceSub: '₹ 9,166 / Sq.Ft · 1,800 sq.ft',
    bhk: 3,
    area: 1800,
    location: { city: 'Pune', address: 'Amanora Park Town, Hadapsar, Pune' },
    status: 'uc',
    statusLabel: 'Under Construction',
    statusDate: 'Possession: Mar 2027',
    rera: true,
    reraId: 'MAHARERA/P52100000192',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Sky Spa', 'Infinity Pool', 'Swarovski Designed Lobby', 'Tennis Courts', 'Township Central Park', '24x7 Security'],
    usps: ['World-first Swarovski embellished residence', 'Within 400-acre self-sufficient township', 'Direct walk to Amanora Mall & schools'],
    enquiries: 85,
    visits: 1060,
  },

  // 30. PRESTIGE GOLFSHIRE SIGNATURE COUNTRY VILLA (BENGALURU) - FOR SALE
  {
    title: 'Prestige Golfshire Signature Country Villa',
    description: 'Opulent 5 BHK country villa sprawling across 8,500 sq.ft set inside Bengaluru’s 275-acre PGA-standard golf resort at the foot of Nandi Hills with private pool.',
    type: 'Villa',
    category: 'property',
    purpose: 'buy',
    price: 98000000,
    priceDisplay: '₹ 9.80 Cr',
    priceSub: '₹ 11,529 / Sq.Ft · 8,500 sq.ft',
    bhk: 5,
    area: 8500,
    location: { city: 'Bengaluru', address: 'Nandi Hills Road, Devanahalli, Bengaluru' },
    status: 'ready',
    statusLabel: 'Ready To Move',
    statusDate: 'Immediate possession',
    rera: true,
    reraId: 'PRM/KA/RERA/1251/446/PR/171120',
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Private Pool', '18-Hole Championship Golf Course Access', 'Clubhouse Falcon', 'JW Marriott Resort Services', 'Private Lawn', 'Helipad'],
    usps: ['Private 18-hole Bob Hunt golf course view', 'Managed by JW Marriott luxury hospitality', 'Bespoke mansion with private temperature pool'],
    enquiries: 53,
    visits: 710,
    isFeatured: true,
  },

  // 31. MY HOME BHOOJA SKY MANSIONS (HYDERABAD) - FOR SALE
  {
    title: 'My Home Bhooja Sky Mansions',
    description: 'Iconic 4 BHK high-rise residence in HITEC City with panoramic views of Hyderabad’s financial district, bio-diversity park, and Durgam Cheruvu cable bridge.',
    type: '4 BHK Apartment',
    category: 'property',
    purpose: 'buy',
    price: 56000000,
    priceDisplay: '₹ 5.60 Cr',
    priceSub: '₹ 13,725 / Sq.Ft · 4,080 sq.ft',
    bhk: 4,
    area: 4080,
    location: { city: 'Hyderabad', address: 'HITEC City, Madhapur, Hyderabad' },
    status: 'ready',
    statusLabel: 'Ready To Move',
    statusDate: 'Immediate possession',
    rera: true,
    reraId: 'TS/HYD/2022/411',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Grand Clubhouse', 'Temperature Controlled Pool', 'Sky Lounge', 'Gymnasium', 'Tennis Courts', '3 Car Parking Bays'],
    usps: ['Hyderabad’s most iconic luxury address', 'Overlooking 100-acre Bio-Diversity Park', 'Direct walk to Mindspace IT SEZ'],
    enquiries: 68,
    visits: 920,
    isFeatured: true,
  },

  // 32. SUN WESTBANK PRIME CORPORATE SUITES (AHMEDABAD) - FOR SALE
  {
    title: 'Sun Westbank Prime Corporate Suites',
    description: 'Riverfront facing premium corporate office space on Ashram Road, Ahmedabad. Equipped with double-height glass lobby and high-speed elevators.',
    type: 'Commercial',
    category: 'property',
    purpose: 'buy',
    price: 19500000,
    priceDisplay: '₹ 1.95 Cr',
    priceSub: '₹ 9,285 / Sq.Ft · 2,100 sq.ft',
    bhk: 0,
    area: 2100,
    location: { city: 'Ahmedabad', address: 'Ashram Road, Sabarmati Riverfront, Ahmedabad' },
    status: 'ready',
    statusLabel: 'Ready To Move',
    statusDate: 'Immediate possession',
    rera: true,
    reraId: 'GJ/AHM/2023/182',
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Central Air Conditioning', 'High Speed Elevators', 'Double Basement Parking', 'Fire Sprinklers', '24x7 Security'],
    usps: ['Direct Sabarmati Riverfront view', 'Prime central business district location', 'High rental yield for corporate head offices'],
    enquiries: 38,
    visits: 510,
  },

  // 33. GOYAL RIVIERA SERENE RIVERSIDE LIVING (AHMEDABAD) - FOR SALE (NEW PROJECT)
  {
    title: 'Goyal Riviera Serene Riverside Living',
    description: 'Modern 2 BHK residential apartment by Goyal & Co in Makarba, Ahmedabad. Built with superior seismic-resistant structure and landscaped courtyards.',
    type: '2 BHK Apartment',
    category: 'project',
    purpose: 'buy',
    price: 7200000,
    priceDisplay: '₹ 72.00 L',
    priceSub: '₹ 5,760 / Sq.Ft · 1,250 sq.ft',
    bhk: 2,
    area: 1250,
    location: { city: 'Ahmedabad', address: 'Makarba, SG Highway, Ahmedabad' },
    status: 'uc',
    statusLabel: 'Under Construction',
    statusDate: 'Possession: Nov 2026',
    rera: true,
    reraId: 'GJ/AHM/2024/0411',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Clubhouse', 'Children Play Area', 'Gymnasium', 'Landscaped Garden', 'CCTV Security', 'Covered Parking'],
    usps: ['Trusted 50+ year legacy builder', '5 minutes from Prahladnagar & SG Highway', 'Serene quiet gated residential enclave'],
    enquiries: 62,
    visits: 840,
  },

  // 34. PANCHSHIL TRUMP TOWERS PRESIDENTIAL RESIDENCE (PUNE) - FOR SALE
  {
    title: 'Panchshil Trump Towers Presidential Residence',
    description: 'Ultra-exclusive 4 BHK single-floor presidential apartment in Kalyani Nagar, Pune. Finished with polished black glass exterior, private elevator, and concierge.',
    type: 'Penthouse',
    category: 'property',
    purpose: 'buy',
    price: 165000000,
    priceDisplay: '₹ 16.50 Cr',
    priceSub: '₹ 27,049 / Sq.Ft · 6,100 sq.ft',
    bhk: 4,
    area: 6100,
    location: { city: 'Pune', address: 'Kalyani Nagar, Pune' },
    status: 'ready',
    statusLabel: 'Ready To Move',
    statusDate: 'Immediate possession',
    rera: true,
    reraId: 'MAHARERA/P52100000781',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
    ],
    amenities: ['Private Elevator', 'Private Lap Pool', 'Trump Concierge', 'Valet Parking', 'Executive Spa', 'Helipad'],
    usps: ['Iconic black glass twin tower architecture', 'Single floor entire private residence', 'World-class 24x7 bespoke concierge'],
    enquiries: 41,
    visits: 580,
    isFeatured: true,
  },
];

const connectDB = require('./config/db');

const seedDB = async () => {
  try {
    await connectDB();
    console.log('MongoDB Connected for seeding.');

    // 1. Seed / Upsert Demo Users
    const demoUsers = [
      {
        name: 'EstateXplorer Administrator',
        email: 'admin@estatexplorer.in',
        password: 'Password@123',
        phone: '+91 98765 00000',
        role: 'admin',
        roles: ['buyer', 'admin', 'builder', 'agent'],
        city: 'Mumbai',
      },
      {
        name: 'Prestige Estates Group',
        email: 'builder@estatexplorer.in',
        password: 'Password@123',
        phone: '+91 98765 00001',
        role: 'builder',
        roles: ['buyer', 'builder'],
        city: 'Bengaluru',
        builderProfile: {
          companyName: 'Prestige Estates Group',
          displayName: 'Prestige Group',
          reraNumber: 'PRM/KA/RERA/1251/446/AG/2023',
          experience: 25,
          totalProjects: 140,
        },
      },
      {
        name: 'Knight Frank Real Estate',
        email: 'agent@estatexplorer.in',
        password: 'Password@123',
        phone: '+91 98765 00002',
        role: 'agent',
        roles: ['buyer', 'agent'],
        city: 'Mumbai',
        agentProfile: {
          agencyName: 'Knight Frank India',
          licenseNumber: 'MAHARERA/A51900000123',
          specialization: 'Luxury Residential & Commercial',
        },
      },
      {
        name: 'Rajesh Singhania',
        email: 'owner@estatexplorer.in',
        password: 'Password@123',
        phone: '+91 98765 00003',
        role: 'owner',
        roles: ['buyer', 'owner'],
        city: 'Delhi',
        ownerProfile: {
          panNumber: 'ABCDE1234F',
          ownershipProofVerified: true,
        },
      },
      {
        name: 'Parth Aadthakkar',
        email: 'buyer@estatexplorer.in',
        password: 'Password@123',
        phone: '+91 98765 00004',
        role: 'buyer',
        roles: ['buyer'],
        city: 'Ahmedabad',
      },
    ];

    const createdUsers = [];
    for (const userData of demoUsers) {
      let user = await User.findOne({ email: userData.email });
      if (!user) {
        user = await User.create(userData);
        console.log(`Created seed user: ${user.name} (${user.role})`);
      } else {
        console.log(`Seed user exists: ${user.name} (${user.role})`);
      }
      createdUsers.push(user);
    }

    const privilegedUsers = createdUsers.filter(u => ['builder', 'agent', 'owner', 'admin'].includes(u.role));

    // 2. Clear and re-seed Properties linked to privileged users
    await Property.deleteMany({});
    
    const propertiesToInsert = propertiesData.map((p, index) => {
      const assignedUser = privilegedUsers[index % privilegedUsers.length];
      return {
        ...p,
        builder: assignedUser._id,
        isActive: true,
      };
    });

    await Property.insertMany(propertiesToInsert);
    console.log(`✅ Successfully seeded ${propertiesToInsert.length} properties linked to MongoDB users!`);

    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding data:', error);
    process.exit(1);
  }
};

seedDB();
