export const trustStats = [
  {
    icon: 'house',
    num: '25,000+',
    label: 'Properties Listed',
  },
  {
    icon: 'shield',
    num: '18,500+',
    label: 'Verified Listings',
  },
  {
    icon: 'users',
    num: '50,000+',
    label: 'Happy Families',
  },
  {
    icon: 'layers',
    num: '1,200+',
    label: 'Trusted Builders',
  },
  // {
  //   icon: 'star',
  //   num: '4.7/5',
  //   label: 'Google Rating',
  // },
  {
    icon: 'checkCircle',
    num: 'RERA',
    label: 'Verified',
  },
  {
    icon: 'clock',
    num: '12+',
    label: 'Years of Trust',
  },
];

export const categories = [
  {
    id: 1,
    title: 'Luxury Villas',
    count: '2,450 Properties',
    desc: 'Spacious villas with premium amenities',
    image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 2,
    title: 'Apartments',
    count: '12,450 Properties',
    desc: 'Modern apartments in prime locations',
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 3,
    title: 'Commercial',
    count: '1,120 Properties',
    desc: 'Office spaces, shops & commercial buildings',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 4,
    title: 'Plots',
    count: '3,245 Properties',
    desc: 'Residential & commercial plots for investment',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 5,
    title: 'Penthouses',
    count: '840 Properties',
    desc: 'Ultra-luxury penthouses with stunning views',
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 6,
    title: 'Farmhouses',
    count: '320 Properties',
    desc: 'Peaceful farmhouses away from the city',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=500&auto=format&fit=crop',
  },
];

export const featuredProperties = [
  {
    id: 1,
    builder: 'DLF Building India',
    name: 'DLF The Camellias',
    location: 'Gurugram, Golf Course Road',
    price: '₹12.50 Cr',
    emi: 'EMI from ₹6.75 L / mo',
    beds: '4 Beds',
    baths: '5 Baths',
    sqft: '3600 sqft',
    parking: '2 Parking',
    status: 'Ready to Move',
    statusType: 'ready',
    verified: true,
    rera: true,
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 2,
    builder: 'Godrej Properties',
    name: 'Godrej Riverine',
    location: 'Sector 44, Noida',
    price: '₹3.25 Cr',
    emi: 'EMI from ₹2.02 L / mo',
    beds: '3 Beds',
    baths: '3 Baths',
    sqft: '1850 sqft',
    parking: '1 Parking',
    status: 'Under Construction',
    statusType: 'construction',
    verified: true,
    rera: true,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=600&auto=format&fit=crop',
  },
  // {
  //   id: 3,
  //   builder: 'Lodha Group',
  //   name: 'Lodha Park',
  //   location: 'Worli, Mumbai',
  //   price: '₹8.90 Cr',
  //   emi: 'EMI from ₹5.50 L / mo',
  //   beds: '4 Beds',
  //   baths: '4 Baths',
  //   sqft: '2800 sqft',
  //   parking: '2 Parking',
  //   status: 'Ready to Move',
  //   statusType: 'ready',
  //   verified: true,
  //   rera: true,
  //   image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=600&auto=format&fit=crop',
  // },
  // {
  //   id: 4,
  //   builder: 'Prestige Group',
  //   name: 'Prestige Lakeside',
  //   location: 'Whitefield, Bangalore',
  //   price: '₹2.10 Cr',
  //   emi: 'EMI from ₹1.30 L / mo',
  //   beds: '2 Beds',
  //   baths: '2 Baths',
  //   sqft: '1250 sqft',
  //   parking: '1 Parking',
  //   status: 'Under Construction',
  //   statusType: 'construction',
  //   verified: true,
  //   rera: true,
  //   image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=600&auto=format&fit=crop',
  // },
];

export const featuredProjects = [
  {
    id: 1,
    builder: 'DLF Building India',
    name: 'DLF Privana West',
    features: [
      '4 & 5 BHK Luxury Residences',
      'World-class clubhouse',
      '5-star security system',
      '80% open green spaces',
    ],
    meta: 'Possession: Dec 2028 · Gurugram, Sector 76',
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=700&auto=format&fit=crop',
  },
  {
    id: 2,
    builder: 'Godrej Properties',
    name: 'Godrej Tropical Isle',
    features: [
      '3 & 4 BHK Premium Homes',
      'Tropical-themed architecture',
      'Resort-style amenities',
      'Near expressway & metro',
    ],
    meta: 'Possession: Mid 2027 · Vikhroli, Mumbai',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=700&auto=format&fit=crop',
  },
];

export const cities = [
  {
    id: 1,
    name: 'Mumbai',
    count: '12,400 Properties',
    price: 'Avg. Price ₹ 28,500 / sqft',
    growth: 'Growth +12.5%',
    image: 'https://images.unsplash.com/photo-1566552881560-0be862a7c445?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 2,
    name: 'Delhi NCR',
    count: '16,200 Properties',
    price: 'Avg. Price ₹ 9,850 / sqft',
    growth: 'Growth +15.3%',
    image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 3,
    name: 'Bangalore',
    count: '14,800 Properties',
    price: 'Avg. Price ₹ 11,200 / sqft',
    growth: 'Growth +13.8%',
    image: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 4,
    name: 'Pune',
    count: '9,450 Properties',
    price: 'Avg. Price ₹ 8,200 / sqft',
    growth: 'Growth +11.2%',
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 5,
    name: 'Hyderabad',
    count: '8,120 Properties',
    price: 'Avg. Price ₹ 8,650 / sqft',
    growth: 'Growth +14.1%',
    image: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 6,
    name: 'Ahmedabad',
    count: '7,640 Properties',
    price: 'Avg. Price ₹ 6,400 / sqft',
    growth: 'Growth +10.9%',
    image: 'https://images.unsplash.com/photo-1596401057633-54a8fe8ef647?q=80&w=800&auto=format&fit=crop',
  },
];

export const whyItems = [
  {
    icon: 'checkBadge',
    title: 'Verified Listings',
    desc: 'Every property is thoroughly verified',
  },
  {
    icon: 'scale',
    title: 'Legal Assistance',
    desc: 'End-to-end legal support',
  },
  {
    icon: 'creditCard',
    title: 'Loan Support',
    desc: 'Get the best home loan deals',
  },
  {
    icon: 'building',
    title: 'Trusted Builders',
    desc: 'Partnered with top real estate brands',
  },
  {
    icon: 'userCheck',
    title: 'Expert Consultants',
    desc: 'Personalized guidance at every step',
  },
  {
    icon: 'heartHandshake',
    title: 'Post Purchase Support',
    desc: "We're with you even after you buy",
  },
];

export const insights = [
  {
    id: 1,
    cat: 'Market Trends',
    title: 'Real Estate Market Outlook 2026: What to Expect',
    meta: 'May 15, 2026 · 5 min read',
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 2,
    cat: 'Buying Guide',
    title: 'Complete Guide to Buying Your First Home',
    meta: 'May 10, 2026 · 7 min read',
    image: 'https://images.unsplash.com/photo-1560520653-9e0e4c89eb11?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 3,
    cat: 'Investment',
    title: 'Top 10 Investment Hotspots in India for 2026',
    meta: 'May 5, 2026 · 6 min read',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 4,
    cat: 'Architecture',
    title: 'Modern Architecture Trends Shaping Real Estate',
    meta: 'Apr 28, 2026 · 4 min read',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 5,
    cat: 'Legal Tips',
    title: 'RERA Guidelines Every Buyer Should Know',
    meta: 'Apr 20, 2026 · 5 min read',
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 6,
    cat: 'Interior Design',
    title: 'Interior Design Ideas for Luxury Homes',
    meta: 'Apr 12, 2026 · 6 min read',
    image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=400&auto=format&fit=crop',
  },
];

export const popularSearches = [
  'Luxury Villas',
  '2 BHK Flats',
  'Under ₹1 Cr',
  'Ready to Move',
  'Near Metro',
  'Commercial Spaces',
];
